export const MOCK_PRODUCTS = [
  // ─── Sarees ───────────────────────────────────────────────────────────────────
  {
    id: 'mock-saree-1',
    title: 'Royal Crimson Kanjivaram',
    type: 'saree',
    base_price: 25650,
    discount_pct: 10,
    published: true,
    category: { id: 'saree-kanchipuram', name: 'Kanchipuram Pattu' },
    images: [{ id: 'img-s1', url: null, color: 'Crimson', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-s1-1', color: 'Crimson', size: '', quantity: 8, sku: 'KNJ-CRM-001' },
      { id: 'v-s1-2', color: 'Navy', size: '', quantity: 5, sku: 'KNJ-NVY-001' },
    ],
  },
  {
    id: 'mock-saree-2',
    title: 'Midnight Blue Banarasi',
    type: 'saree',
    base_price: 18999,
    discount_pct: 8,
    published: true,
    category: { id: 'saree-banarasi', name: 'Banarasi Silk' },
    images: [{ id: 'img-s2', url: null, color: 'Blue', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-s2-1', color: 'Blue', size: '', quantity: 12, sku: 'BNR-BLU-001' },
      { id: 'v-s2-2', color: 'Gold', size: '', quantity: 6, sku: 'BNR-GLD-001' },
    ],
  },
  {
    id: 'mock-saree-3',
    title: 'Emerald Green Patola',
    type: 'saree',
    base_price: 32500,
    discount_pct: 5,
    published: true,
    category: { id: 'saree-pochampally', name: 'Pochampally Ikat' },
    images: [{ id: 'img-s3', url: null, color: 'Green', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-s3-1', color: 'Green', size: '', quantity: 4, sku: 'PTL-GRN-001' },
      { id: 'v-s3-2', color: 'Red', size: '', quantity: 3, sku: 'PTL-RED-001' },
    ],
  },
  {
    id: 'mock-saree-4',
    title: 'Golden Tissue Kanjivaram',
    type: 'saree',
    base_price: 45000,
    discount_pct: 12,
    published: true,
    category: { id: 'saree-kanchipuram', name: 'Kanchipuram Pattu' },
    images: [{ id: 'img-s4', url: null, color: 'Gold', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-s4-1', color: 'Gold', size: '', quantity: 3, sku: 'KNJ-GLD-001' },
      { id: 'v-s4-2', color: 'Cream', size: '', quantity: 5, sku: 'KNJ-CRM-002' },
    ],
  },
  {
    id: 'mock-saree-5',
    title: 'Silver Zari Tussar Silk',
    type: 'saree',
    base_price: 12800,
    discount_pct: 15,
    published: true,
    category: { id: 'saree-tussar', name: 'Tussar' },
    images: [{ id: 'img-s5', url: null, color: 'Silver', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-s5-1', color: 'Silver', size: '', quantity: 10, sku: 'TSR-SLV-001' },
      { id: 'v-s5-2', color: 'Ivory', size: '', quantity: 7, sku: 'TSR-IVR-001' },
    ],
  },

  // ─── Dresses ──────────────────────────────────────────────────────────────────
  {
    id: 'mock-dress-1',
    title: 'Ivory Chanderi Anarkali',
    type: 'dress',
    base_price: 8999,
    discount_pct: 10,
    published: true,
    category: { id: 'dress-anarkali', name: 'Anarkali' },
    images: [{ id: 'img-d1', url: null, color: 'Ivory', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-d1-1', color: 'Ivory', size: 'S', quantity: 6, sku: 'ANK-IVR-S' },
      { id: 'v-d1-2', color: 'Pink', size: 'M', quantity: 8, sku: 'ANK-PNK-M' },
      { id: 'v-d1-3', color: 'Ivory', size: 'L', quantity: 4, sku: 'ANK-IVR-L' },
    ],
  },
  {
    id: 'mock-dress-2',
    title: 'Rose Gold Lehenga Set',
    type: 'dress',
    base_price: 35500,
    discount_pct: 7,
    published: true,
    category: { id: 'dress-lehenga', name: 'Lehenga' },
    images: [{ id: 'img-d2', url: null, color: 'Pink', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-d2-1', color: 'Rose', size: 'M', quantity: 3, sku: 'LHG-RSE-M' },
      { id: 'v-d2-2', color: 'Maroon', size: 'L', quantity: 5, sku: 'LHG-MRN-L' },
    ],
  },
  {
    id: 'mock-dress-3',
    title: 'Teal Sharara Ensemble',
    type: 'dress',
    base_price: 15200,
    discount_pct: 12,
    published: true,
    category: { id: 'dress-sharara', name: 'Sharara' },
    images: [{ id: 'img-d3', url: null, color: 'Teal', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-d3-1', color: 'Teal', size: 'S', quantity: 7, sku: 'SHR-TEL-S' },
      { id: 'v-d3-2', color: 'Gold', size: 'M', quantity: 4, sku: 'SHR-GLD-M' },
      { id: 'v-d3-3', color: 'Teal', size: 'XL', quantity: 3, sku: 'SHR-TEL-XL' },
    ],
  },
  {
    id: 'mock-dress-4',
    title: 'Blush Pink Palazzo Set',
    type: 'dress',
    base_price: 6450,
    discount_pct: 8,
    published: true,
    category: { id: 'dress-palazzo', name: 'Palazzo Set' },
    images: [{ id: 'img-d4', url: null, color: 'Pink', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-d4-1', color: 'Pink', size: 'S', quantity: 10, sku: 'PLZ-PNK-S' },
      { id: 'v-d4-2', color: 'White', size: 'M', quantity: 8, sku: 'PLZ-WHT-M' },
      { id: 'v-d4-3', color: 'Pink', size: 'L', quantity: 6, sku: 'PLZ-PNK-L' },
    ],
  },
  {
    id: 'mock-dress-5',
    title: 'Midnight Gown Collection',
    type: 'dress',
    base_price: 22000,
    discount_pct: 5,
    published: true,
    category: { id: 'dress-gown', name: 'Gown' },
    images: [{ id: 'img-d5', url: null, color: 'Black', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-d5-1', color: 'Black', size: 'M', quantity: 4, sku: 'GWN-BLK-M' },
      { id: 'v-d5-2', color: 'Silver', size: 'L', quantity: 3, sku: 'GWN-SLV-L' },
    ],
  },

  // ─── Gold / Jewellery ─────────────────────────────────────────────────────────
  {
    id: 'mock-gold-1',
    title: 'Lakshmi Temple Necklace',
    type: 'jewellery',
    base_price: 125000,
    discount_pct: 5,
    published: true,
    category: { id: 'gold-temple', name: 'Temple Jewellery' },
    images: [{ id: 'img-g1', url: null, color: 'Gold', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-g1-1', color: 'Gold', size: '20g', quantity: 2, sku: 'TMP-GLD-20G' },
      { id: 'v-g1-2', color: 'Gold', size: '50g', quantity: 1, sku: 'TMP-GLD-50G' },
    ],
  },
  {
    id: 'mock-gold-2',
    title: 'Kundan Bridal Set',
    type: 'jewellery',
    base_price: 245000,
    discount_pct: 8,
    published: true,
    category: { id: 'gold-kundan', name: 'Kundan' },
    images: [{ id: 'img-g2', url: null, color: 'Gold', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-g2-1', color: 'Gold', size: '50g', quantity: 1, sku: 'KND-GLD-50G' },
      { id: 'v-g2-2', color: 'Gold', size: '20g', quantity: 2, sku: 'KND-GLD-20G' },
    ],
  },
  {
    id: 'mock-gold-3',
    title: 'Rose Gold Jhumka Pair',
    type: 'jewellery',
    base_price: 45500,
    discount_pct: 10,
    published: true,
    category: { id: 'gold-jhumka', name: 'Jhumka' },
    images: [{ id: 'img-g3', url: null, color: 'Gold', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-g3-1', color: 'Rose Gold', size: '5g', quantity: 6, sku: 'JHM-RSG-5G' },
      { id: 'v-g3-2', color: 'Rose Gold', size: '10g', quantity: 3, sku: 'JHM-RSG-10G' },
    ],
  },
  {
    id: 'mock-gold-4',
    title: 'Antique Bangles Set of 4',
    type: 'jewellery',
    base_price: 78000,
    discount_pct: 6,
    published: true,
    category: { id: 'gold-bangles', name: 'Bangles' },
    images: [{ id: 'img-g4', url: null, color: 'Gold', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-g4-1', color: 'Gold', size: '10g', quantity: 4, sku: 'BNG-GLD-10G' },
      { id: 'v-g4-2', color: 'Gold', size: '20g', quantity: 2, sku: 'BNG-GLD-20G' },
    ],
  },
  {
    id: 'mock-gold-5',
    title: 'Pearl Meenakari Pendant',
    type: 'jewellery',
    base_price: 55000,
    discount_pct: 12,
    published: true,
    category: { id: 'gold-meenakari', name: 'Meenakari' },
    images: [{ id: 'img-g5', url: null, color: 'Gold', is_primary: true, placeholder: true }],
    variants: [
      { id: 'v-g5-1', color: 'Gold', size: '5g', quantity: 5, sku: 'MNK-GLD-5G' },
      { id: 'v-g5-2', color: 'Gold', size: '10g', quantity: 3, sku: 'MNK-GLD-10G' },
    ],
  },
];
