/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutShippingRouteImport } from './routes/checkout.shipping'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutAddressRouteImport } from './routes/checkout.address'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutShippingRoute = CheckoutShippingRouteImport.update({
  id: '/checkout/shipping',
  path: '/checkout/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/checkout/review',
  path: '/checkout/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/checkout/payment',
  path: '/checkout/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutAddressRoute = CheckoutAddressRouteImport.update({
  id: '/checkout/address',
  path: '/checkout/address',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/checkout/shipping': typeof CheckoutShippingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/cart': typeof CartRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/checkout/shipping': typeof CheckoutShippingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/login': typeof AccountLoginRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/register': typeof AccountRegisterRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/checkout/shipping': typeof CheckoutShippingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/cart'
    | '/contact-us'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/wishlist'
    | '/account/addresses'
    | '/account/login'
    | '/account/orders'
    | '/account/profile'
    | '/account/register'
    | '/category/$slug'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/checkout/shipping'
    | '/checkout/success'
    | '/product/$slug'
    | '/account/'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/cart'
    | '/contact-us'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/wishlist'
    | '/account/addresses'
    | '/account/login'
    | '/account/orders'
    | '/account/profile'
    | '/account/register'
    | '/category/$slug'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/checkout/shipping'
    | '/checkout/success'
    | '/product/$slug'
    | '/account'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/cart'
    | '/contact-us'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/wishlist'
    | '/account/addresses'
    | '/account/login'
    | '/account/orders'
    | '/account/profile'
    | '/account/register'
    | '/category/$slug'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/checkout/shipping'
    | '/checkout/success'
    | '/product/$slug'
    | '/account/'
    | '/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  ContactUsRoute: typeof ContactUsRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CheckoutAddressRoute: typeof CheckoutAddressRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
  CheckoutShippingRoute: typeof CheckoutShippingRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/shipping': {
      id: '/checkout/shipping'
      path: '/checkout/shipping'
      fullPath: '/checkout/shipping'
      preLoaderRoute: typeof CheckoutShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/checkout/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/address': {
      id: '/checkout/address'
      path: '/checkout/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof CheckoutAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  ContactUsRoute: ContactUsRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  CheckoutAddressRoute: CheckoutAddressRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
  CheckoutShippingRoute: CheckoutShippingRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
